### PR TITLE
#70 - WCAG 2 level AA color contrast recommendation

### LINKED ISSUE #70: WCAG 2 level AA recommendation in the message
**Describe the Feature you want to end**
Currently, the user has to depend on her/his judgment for deciding the right "Color Readability". 
This can be tricky/wrong in some situations as this is a manual and partially subjective decision. 
Rather than just leaving the user on her taste/judgment - we should also give a hint of whether the current colors pass the WCAG 2 level AA contrast ratio thresholds.

**Expected behavior**
Users should be informed about the current contrast ratio.

**Screenshots**
A possible solution is to include the hint in the current message text.
image

**Additional context (optional )**
- Read more about [WCAG 2 contrast threshold](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html)

### PR DESCRIPTION
**Pull request by ankitwww**
Fixes #70 - shows WCAG 2 level color contrast message to user

### Implementation details
Added message about the contrast ratio in message section.

image
image

### Testing Steps
- Change text and background colors and observe that the contrast message should change. The recommendation text should also change based on whether the ratio is greater than 4.5.

---

Checklist:

- [x] Pull Request title is good
- [x] Commit message is good (copy the Pull Request description to the commit message)
- [x] Tested code locally
- [-] Covered by automated tests
- [ ] Approved by the author

### CODE REVIEW

**Comment by ankitwww** [comment]
@HridoyHazard could you please take a look on the PR?

**Comment by HridoyHazard** [comment]
can you plz resolve the conflicts ?

**Comment by ankitwww** [comment]
@HridoyHazard - Resolved for now. We should probably break things into diff components to avoid frequent merge conflicts. Please let me know if you want me to create a ticket and work on it.

**Comment by ankitwww** [comment]
Hey @HridoyHazard - Feel free to reject this PR if you don't think it is valuable. At least don't sit on this for long. TIA

**Pull request merged**
