### PR TITLE
Refactor code issue #55

### PR DESCRIPTION
**Pull request by jsapuyesp**
### The Problem/Feature

Problems in the code, because all the app was inside the `<header></header>` tag.

### Implementation details

All coding in the app, i change the Home.html and the Home.css class and tags

---

Checklist:

- [ x ] Pull Request title is good
- [ x ] Commit message is good (copy the Pull Request description to the commit message)
- [ x ] Tested code locally
- [ ] Covered by automated tests
- [ ] Approved by the author

### CODE REVIEW

**Comment by jsapuyesp** [comment]
About the update of the app:
imagen


The app it was separated in 3 sections: `<header></header>`, `<main></main>`, `<footer></footer>`


imagen

And the css code is refactored too...

**Comment by HridoyHazard** [comment]
fix your conflicts first

**Comment by jsapuyesp** [comment]
The conflicts it was solved!

**Comment by HridoyHazard** [comment]
i can't merge it due to conflicts 
can you plz check and fix the desired conflicts which you're creating

**Comment by jsapuyesp** [comment]
The problem happens because you first accept other PR that affect the code I am refactoring, please check this PR first before the others to avoid these conflicts!

**Pull request merged**
