### PR TITLE
Added Footer Component

### PR DESCRIPTION
**Pull request by Gulshan-11**
I have added footer component.

### CODE REVIEW

**Comment by HridoyHazard** [comment]
this branch has conflict plz fix it

**Comment by Gulshan-11** [comment]
Hey @HridoyHazard i have resolved the issues 
 closes #23

**Comment by Gulshan-11** [comment]
resolved conflicts

**Comment by Gulshan-11** [comment]
hey @HridoyHazard can you look into this. I have resolved the issue

**Comment by Gulshan-11** [comment]
Hey @HridoyHazard please look into this

**Comment by Gulshan-11** [comment]
Hey @HridoyHazard it's been days since I raised a pr 
Please look into this

**Pull request closed without merging**
